replicaCount: 1

image:
  repository: 521737778660.dkr.ecr.us-east-1.amazonaws.com/artemis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "2.0.0"

  imagePullSecrets:
    -regcred


